config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations"
  }
  resources :users, only: [:show, :index]
  resources :categories do
    resources :products do
      resources :reviews
    end
  end

  root 'categories#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  validates :name, uniqueness: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  has_many :reviews

  validates_presence_of :title, :description, :price, :user_id

  validates_format_of :price, with: /\A\d+(\.\d{1,2})?\z/, on: :create

  def average_rating
    return reviews.pluck(:rating).reduce(:+) / reviews.size.to_f if reviews.any?
    0
  end

  def owner(user)
    return true if self.user == user
    false
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

  validates_presence_of :content, :rating, :user_id

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews
  has_many :products
  validates_presence_of :firstname, :lastname

  scope :users_only, -> { where(admin: false) }
  scope :admins_only, -> { where(admin: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  def authorize_admin!
    logger.error "Attempt to access admin path by user with id:#{current_user.id}"
    redirect_to root_path, :flash => { :error => "You are not allowed to see this page." }  unless current_user && current_user.admin?
  end

  def redirect_if_not_product_owner
    unless product.user == current_user
      logger.error "Attempt to access not own product edit path by user with id:#{current_user.id}"
      redirect_to category_product_url(params[:category_id], params[:id]), :flash => { :error => "You are not allowed to edit this product." }
    end
  end

  protect_from_forgery with: :exception

  private

  def record_not_found
    redirect_to root_path, flash: { error: "Sorry, not found." }
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  before_action :authorize_admin!, only: [:new, :edit, :update, :destroy, :create] # should be can can, but not for only one controller.



  expose(:categories)
  expose(:category)
  expose(:product) { Product.new }

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    self.category = Category.new(category_params)

    if category.save
      redirect_to category, notice: 'Category was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if category.update(category_params)
      redirect_to category, notice: 'Category was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  before_action :redirect_if_not_product_owner, only: [:edit, :update, :destroy]

  expose(:category)
  expose(:products)
  expose(:product)
  expose(:review) { Review.new }
  expose_decorated(:reviews, ancestor: :product)

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    self.product = Product.new(product_params)
    product.user = current_user
    if product.save
      category.products << product
      redirect_to category_product_url(category, product), notice: 'Product was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if self.product.update(product_params)
      redirect_to category_product_url(category, product), notice: 'Product was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /products/1
  def destroy
    product.destroy
    redirect_to category_url(product.category), notice: 'Product was successfully destroyed.'
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id, :user_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]

#IMHO user should create only one review per product, but there was not such an issue.

  expose(:review)
  expose(:product)
  expose(:category)

  def edit
  end

  def new
  end

  def create
    self.review = Review.new(review_params)
    review.user = current_user
    if review.save
      product.reviews << review
      redirect_to category_product_url(product.category, product), notice: 'Review was successfully created.'
    else
      render action: 'new'
    end
  end

  def destroy
    review.destroy
    redirect_to category_product_url(product.category, product), notice: 'Review was successfully destroyed.'
  end

  private
  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:email, :password, :password_confirmation, :firstname, :lastname)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:email, :password, :password_confirmation, :firstname, :lastname,
               :current_password, :about_me)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  expose_decorated(:users) { User.users_only.decorate }
  expose_decorated(:user)


  def show
  end

  def index
  end

  private

  def user_params
    params.require(:user).permit
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.haml
= form_for category do |f|
  - if category.errors.any?
    #error_explanation
      %ul
        - category.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-primary'
  %br
  %br

app/views/categories/edit.html.haml
= render :layout => "layouts/center_cols_set" do
  %h1 Editing category

  = render 'form'
  %br
  = link_to 'Show', category, class: 'btn btn-primary'
  \|
  = link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/index.html.haml
= render :layout => "layouts/center_cols_set" do
  - if categories.any?
    %h1 Listing categories

    %table.table
      %tr
        %th Name
        %th
        - if current_user && current_user.admin
          %th
          %th

      - categories.each do |category|
        %tr
          %td= category.name
          %td= link_to 'Show', category
          - if current_user && current_user.admin
            %td= link_to 'Edit', edit_category_path(category)
            %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }

    %br
  - else
    %h1 Sorry, there's no categories yet.
  = link_to 'New Category', new_category_path if current_user && current_user.admin 

app/views/categories/new.html.haml
= render :layout => "layouts/center_cols_set" do
  %h1 New category

  = render 'form'

  = link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/categories/show.html.haml
= render :layout => "layouts/center_cols_set" do
  %p
    %b Name:
    = category.name

  %p
    - category.products.each do |product|
      = link_to product.title, category_product_path(product.category, product)
  %p
    = link_to 'All products', category_products_path(category)
    %h3 New product
    = render 'products/form'

  = link_to 'Edit', edit_category_path(category) if current_user && current_user.admin
  #br
  = link_to 'Back', categories_path, class: 'btn btn-primary'

app/views/layouts/_center_cols_set.haml
.col-lg-3.col-sm-2
.col-lg-6.col-sm-8.col-xs-12
  =yield

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head
    %title Netguru Workshops
    %meta{ charset: 'utf-8' }/
    %meta{ content: 'IE=Edge,chrome=1', 'http-equiv' => 'X-UA-Compatible' }/
    %meta{ content: 'width=device-width, initial-scale=1.0', name: 'viewport' }/
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          =link_to AppConfig.workshops_name, root_path, class: "navbar-brand"
        %p.navbar-text.navbar-right
          = link_to 'Users', users_path
          - if user_signed_in?
            = link_to 'Edit profile', edit_user_registration_path
            = link_to('Logout', destroy_user_session_path, :method => :delete)
          - else
            = link_to('Sign in', new_user_session_path, :method => :get)
    .container-fluid
      .starter-template
      - if flash[:notice]
        .alert.alert-success= flash[:notice]
      - if flash[:error]
        .alert.alert-danger= flash[:error]
      .row
        .col-lg-12
          = yield

app/views/products/_form.html.haml
= form_for [category, product] do |f|
  - if product.errors.any?
    #error_explanation
      %ul
        - product.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .form-group
    = f.label :price
    = f.text_field :price, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-primary'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', category_product_path(category, product)
\|
= link_to 'Back', category_path(category)

app/views/products/index.html.haml
- if products.any?
  %h1 Listing products

  %table.table
    %tr
      %th Title
      %th Description
      %th Price
      %th Rate
      %th
      - if current_user && current_user.admin
        %th
        %th


    - products.each do |product|
      %tr
        %td= product.title
        %td= product.description
        %td= product.price
        %td= product.average_rating
        %td= link_to 'Show', category_product_path(product.category, product)
        - if current_user && product.owner(current_user)
          %td= link_to 'Edit', edit_category_product_path(product.category, product) 
          %td= link_to 'Destroy', category_product_path(product.category, product), method: :delete, data: { confirm: 'Are you sure?' }
- else
  %h1 Sorry, there's no products for this category yet.
%br

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', category_products_path

app/views/products/show.html.haml
= render :layout => "layouts/center_cols_set" do
  %p
    %b Title:
    = product.title
  %p
    %b Description:
    = product.description
  %p
    %b Price:
    = product.price

  %p
    %b Average Rate
    = product.average_rating

  %p
    %b Category
    = product.category.name

  %h3 Reviews
  = render 'reviews/form'
  %br
  = render reviews

  = link_to 'Edit', edit_category_product_path(category.id, product.id) if current_user && product.owner(current_user)
  %br
  = link_to 'Back', category_products_path, class: 'btn btn-primary'

app/views/reviews/_form.html.haml
= simple_form_for [category, product, review] do |f|
  - if review.errors.any?
    #error_explanation
      %ul
        - review.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :content
    = f.text_area :content, class: 'form-control'
  .form-group
    = f.input :rating, collection: 1..5, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-primary'

app/views/reviews/_review.html.haml
%p= review.content
%p
  %b= review.rating
  %em= review.author
  %br
  %br

app/views/reviews/new.html.haml
= render 'reviews/form'
= link_to 'Back', category_product_path(category, product), class: 'btn btn-primary'

app/views/users/index.html.haml
- if users.any?
  = render :layout => "layouts/center_cols_set" do
    %h1 Listing Users
    %table.table
      %tr
        %th Name
        %th Email
      - users.each do |user|
        %tr
          %td= link_to user.full_name, user_path(user.id)
          %td= user.email
- else
  %h1 Sorry, there's no users yet.

app/views/users/show.html.haml
= render :layout => "layouts/center_cols_set" do
  %p
    %b First Name:
    = user.firstname.capitalize
  %p
    %b Last Name:
    = user.lastname.capitalize
  %p
    %b Email:
    = user.email
  %p
    %b About Me:
    = user.about_me.html_safe unless user.about_me.nil?
  %p
  %p
    -if user.reviews.any?
      .col-lg-6.col-sm-8.col-xs-12
        %b Last Reviews:
        %br
        %br
          %table.table
            %tr
              %th Name
              %th Rate
              %th Product
              %th Date
            = user.last_reviews.html_safe